const records = [
    {
        dn: 'Forbidden Scroll',
        name: 'forbiddenScroll', 
        itemType: 'raceChanger',// enhancer // blessing giver
        choices: [
            {
                dn: "Elf",
                imgName: "elfrace",
                plusTo: { hp: 100, sp: 800, mp: 1000, spd: 3.5, sword: 10, def: 10, magic: 3, core: 10}
            },
            {
                dn: "Divine",
                imgName: "divinerace",
                plusTo: { hp: 1000, sp: 600, mp: 600, spd: 2, sword: 10, def: 10, magic: 3, core: 10}
            },
            {
                dn: "Demon",
                imgName: "demonrace",
                plusTo: { hp: 1000, sp: 40, mp: 2500, spd: 1, sword: 10, def: 10, magic: 50 , core: 10}
            },
        ],
        origPrice: 50000,
        secondPrice: 36000,
        desc: "A scroll that can change a normal human race",
        rarity: 10,
        notLootIn: ["heartland", "dungeon"]
    },
    {
        dn: 'Goblin Tooth',
        name: 'goblinTooth', 
        itemType: 'loot',
        origPrice: 40,
        secondPrice: 20,
        desc: "You can determine a goblin's strength by its tooth",
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Fabric',
        name: 'fabric', 
        itemType: 'loot',
        origPrice: 30,
        secondPrice: 20,
        desc: "this can also be used for crafting medicines and weapon",
        rarity: 10,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Leaves',
        name: "leaves",
        itemType: "loot",
        desc: "A bunch of big and small leaves from the tree",
        origPrice: 5,
        secondPrice: 0,
        rarity: 10,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Stone',
        name: "stone",
        itemType: "loot",
        desc: "essential for making crafts",
        origPrice: 5,
        secondPrice: 2,
        rarity: 0,
        notLootIn: []
    },
    {
        dn: 'Berries',
        name: "berries",
        itemType: "food",
        desc: "this fruit can replenish your stamina",
        origPrice: 5,
        secondPrice: 2,
        rarity: 10,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'small potion',
        name: "spotion",
        itemType: "food",
        desc: "A small potion that can generate your life for an amount",
        origPrice: 100,
        secondPrice: 100,
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: 'medium potion',
        name: "mpotion",
        itemType: "food",
        desc: "A Medium potion that can generate your life for an amount",
        origPrice: 300,
        secondPrice: 300,
        rarity: 20,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: 'big potion',
        name: "bigpotion",
        itemType: "food",
        desc: "A Big potion that can generate your life for an amount",
        origPrice: 500,
        secondPrice: 500,
        rarity: 3,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: 'Atropine',
        name: "poisonAntidote",
        itemType: "food",
        desc: "This antidote is best used for poisons, Only good herbs expert can craft such antidote",
        origPrice: 500,
        secondPrice: 500,
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        name: "beerliquor",
        dn: "Tavern Beer",
        origPrice: 150,
        secondPrice: 60,
        itemType: "food",
        desc: "delicate taste",
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        name: "whiskeyliquor",
        dn: "Whiskey bronze",
        origPrice: 150,
        secondPrice: 60,
        itemType: "food",
        desc: "delicate taste",
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        name: "tanduayliquor",
        dn: "Tanduay Rum",
        origPrice: 100,
        secondPrice: 60,
        itemType: "food",
        desc: "delicate taste",
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: 'Minotaur meat',
        name: "minMeatRaw",
        itemType: "food",
        desc: "taste like an ordinary meat, best when cooked",
        origPrice: 100,
        secondPrice:40,
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: 'Minotaur meat',
        name: "minMeatCooked",
        itemType: "food",
        desc: "A meat that is good for traveling also great taste",
        origPrice: 120,
        secondPrice:40,
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: 'Rabbit meat',
        name: "rabbitMeatRaw",
        itemType: "food",
        desc: "taste like an ordinary meat, best when cooked",
        origPrice: 100,
        secondPrice:40,
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: 'Rabbit meat',
        name: "rabbitMeatCooked",
        itemType: "food",
        desc: "Nourishing meat that will fill your stomach, can be cooked as stew",
        origPrice: 90,
        secondPrice:40,
        rarity: 10,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: 'Red Beryl',
        name: "redberyl",
        itemType: "loot",
        desc: "This crytal is rare to find they commonly use this for crafting powerful sword and equipments",
        origPrice: 15500,
        secondPrice: 12000,
        rarity: 3,
        notLootIn: ["heartland"]
    },
    {
        dn: 'Azurite',
        name: "azurite",
        itemType: "loot",
        desc: "It takes its color intensity from the copper element and it's crystals tend to be monoclinic",
        origPrice: 1000,
        secondPrice: 500,
        rarity: 2,
        notLootIn: ["heartland"]
    },
    { 
        dn: 'Masfina Blade',
        name: 'masfinaBlade', 
        itemType: 'sword',
        desc: "Masfina Blade's Replica, It has almost the same sharpness of the origin but very fragile",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "vipcore", qnty: 2, forgeChance: 8},
        plusDmg: 80,
        cState: 1400,
        durability: 1400,
        rarity: 2,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Staff Of Mare',
        name: 'staffofmare', 
        itemType: 'sword',
        desc: "Staff Of Wizards, Commonly they used this as a tool to control magic",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "gobcore", qnty: 2, forgeChance: 6},
        plusDmg: 10,
        plusMag: 30,
        cState: 5000,
        durability: 5000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Oak Blade',
        name: 'oakblade', 
        itemType: 'sword',
        desc: "One of the most influential of the early swords that arose during the Bronze Age",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "mincore", qnty: 2, forgeChance: 6},
        plusDmg: 35,
        plusMag: 30,
        cState: 5000,
        durability: 5000,
        rarity: 2,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Grimthor Blade',
        name: 'grimthor', 
        itemType: 'sword',
        desc: "Enrage Sword, grimthor can kill any small monsters",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "vipcore", qnty: 2, forgeChance: 6},
        plusDmg: 10,
        plusMag: 30,
        cState: 5000,
        durability: 5000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Falkata Steel',
        name: 'falkata', 
        itemType: 'sword',
        desc: "One of the most influential of the early swords that arose during the Bronze Age",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 6},
        plusDmg: 10,
        plusMag: 30,
        cState: 5000,
        durability: 5000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Red Prince',
        name: 'redprince', 
        itemType: 'sword',
        desc: "A terrifying sword that has blackness inside, it can unleash hell itself",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "vipcore", qnty: 2, forgeChance: 6},
        plusDmg: 40,        
        plusMag: 30,
        cState: 5000,
        durability: 5000,
        rarity: 2,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Lumin Sword',
        name: 'normal', 
        itemType: 'sword',
        desc: "many battles have fought and this sword has the most experience",
        origPrice: 3400,
        secondPrice: 2000,
        plusDmg: 17,
        cState: 3000,
        durability:3000,
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 7},
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Blade Fury',
        name: 'bladefury', 
        itemType: 'sword',
        desc: "a fury sword used by old heroes",
        origPrice: 3400,
        secondPrice: 2000,
        plusDmg: 35,
        cState: 4000,
        durability:4000,
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 3},
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Hunting Sword',
        name: 'huntingsword', 
        itemType: 'sword',
        desc: "sword used for hunting boar and small monsters",
        origPrice: 2000,
        secondPrice: 500,
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 10},
        plusDmg: 13,
        cState: 2000,
        durability: 2000,
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Wooden Stick',
        name: 'stick', 
        itemType: 'sword',
        desc: "useful weapon for self defense",
        origPrice: 400,
        secondPrice: 80,
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 0},
        plusDmg: 10,
        cState: 1000,
        durability: 1000,
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Grim Blue',
        name: 'grimblue', 
        itemType: 'sword',
        desc: "one of its kind, crafted by the great maggos in its time",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 7},
        plusDmg: 35,
        cState: 5000,
        durability: 5000,
        rarity: 2,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Drakfoid',
        name: 'drakfoid', 
        itemType: 'sword',
        desc: "A sword that on par to it's kind the sword can slay hundreds of demons",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 4},
        plusDmg: 45,
        cState: 5000,
        durability: 5000,
        rarity: 3,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Majesty',
        name: 'majesty', 
        itemType: 'sword',
        desc: "A Blazing Sword, Known for It's mixture of gold red and black, Many demons life has been sealed in this sword",
        origPrice: 7000,
        secondPrice: 4000,
        craftMaterial: { name: "bluemincore", qnty: 2, forgeChance: 4},
        plusDmg: 130,
        cState: 6000,
        durability: 6000,
        rarity: 4,
        notLootIn: ["dungeon"]
    },
    { 
        dn: "Golem's Birth",
        name: 'golemsbirth', 
        itemType: 'sword',
        desc: "A Robust Sword, Known for It's hardness, You will get tired but never the sword.",
        origPrice: 7000,
        secondPrice: 4000,
        craftMaterial: { name: "golemcore", qnty: 1, forgeChance: 10},
        plusDmg: 45,
        cState: 3000,
        durability: 3000,
        rarity: 3,
        notLootIn: ["dungeon"]
    },
    { 
        dn: "Demons Idle",
        name: 'demonsidle', 
        itemType: 'sword',
        desc: "A sword that lights on the dark, It was the origin of the cursed swords",
        origPrice: 7000,
        secondPrice: 4000,
        craftMaterial: { name: "bluemincore", qnty: 2, forgeChance: 5},
        plusDmg: 90,
        cState: 6000,
        durability: 6000,
        rarity: 4,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Ruzty Sword',
        name: 'ruztysword', 
        itemType: 'sword',
        desc: "it's rust can inflict your enemy with tetano",
        origPrice: 3400,
        secondPrice: 2000,
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 8},
        plusDmg: 40,
        cState: 5000,
        durability: 5000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Dagger',
        name: 'dagger', 
        itemType: 'sword',
        origPrice: 100,
        plusDmg: 10,
        secondPrice: 20,
        desc: "Assasin's favorite weapon, useful for survival",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 0},
        plusDmg: 15,
        cState: 1000,
        durability: 1000,
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    { 
        dn: 'Dragon Spear',
        name: 'dragonSpear',
        itemType: 'sword',
        desc: "holding this powerful spear can make you powerful against any foes",
        plusDmg: 40,
        origPrice: 6000,
        secondPrice: 5500,
        craftMaterial: { name: "vipcore", qnty: 2, forgeChance: 7},
        plusDmg: 40,
        cState: 5000,
        durability: 5000,
        rarity: 2,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Dger Spear',
        name: 'dgerSpear', 
        itemType: 'sword',
        origPrice: 3000,
        plusDmg: 30,
        secondPrice: 20,
        cState: 4000,
        durability:4000,
        desc: "Light and easy to throw spear, It camouflages in the dark",
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 8},
        rarity: 2,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Sarpion",
        name: 'sarpion', 
        itemType: 'sword',
        origPrice: 2000,
        plusDmg: 20,
        secondPrice: 1000,
        cState: 4000,
        durability:4000,
        desc: "A heavy pointed sword, No mercy on your enemy",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 9},
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Village Spear",
        name: 'villageSpear', 
        itemType: 'sword',
        origPrice: 300,
        plusDmg: 15,
        secondPrice: 140,
        cState: 500,
        durability:500,
        desc: "A Pointed Spear useful for throwing, good for hunting",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 0},
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'big rod',
        name: 'rod', 
        itemType: 'sword',
        origPrice: 100,
        plusDmg: 60,
        secondPrice: 1000,
        desc: "A heavy swing from the user will create a large impact on the enemy",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 0},
        plusDmg: 12,
        cState: 500,
        durability: 500,
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Pickaxe',
        name: 'pickaxe', 
        itemType: 'sword',
        origPrice: 100,
        plusDmg: 60,
        secondPrice: 1000,
        desc: "Essential for minning and can also be used as a weapon",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 0},
        plusDmg: 6,
        cState: 4000,
        durability: 4000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Hydra Armor',
        name: 'hydra', 
        itemType: 'armor', 
        plusDef: 18, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 5000,
        secondPrice: 3000,
        desc: "a noble's armor the armor is light but strong as destruction",
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 9},
        cState: 4000,
        durability: 4000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Chief Plate',
        name: 'chiefplate', 
        itemType: 'armor', 
        plusDef: 4, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 5000,
        secondPrice: 3000,
        desc: "a replica of Chief Hanzon armor, the plate is made by bronze",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 10},
        cState: 2400,
        durability: 2400,
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Clad Armor',
        name: 'cladarmor', 
        itemType: 'armor', 
        plusDef: 19, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 5000,
        secondPrice: 3000,
        desc: "This armor is simple and light. Best for swinging swords",
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 10},
        cState: 4000,
        durability: 4000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Karpa Scale',
        name: 'karparmor', 
        itemType: 'armor', 
        plusDef: 48, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 10000,
        secondPrice: 6000,
        desc: "This armor is huge and heavy but the no one has seen died wearing this armor",
        craftMaterial: { name: "vipcore", qnty: 3, forgeChance: 7},
        cState: 6000,
        durability: 6000,
        rarity: 2,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Karba Armor',
        name: 'karba', 
        itemType: 'armor', 
        plusDef: 20, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 5000,
        secondPrice: 3000,
        desc: "this armor is famous to it's known leather, A farmer would say they are invinsible when wearing this armor",
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 7},
        cState: 4000,
        durability: 4000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: "First Born Helmet",
        name: 'firstborn', 
        itemType: 'helmet', 
        plusDef: 5, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 2400,
        secondPrice: 2000,
        desc: "Use this helmet if you're out for adventuring.",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 10},
        cState: 4000,
        durability: 4000,
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    {
        dn: "karori",
        name: 'karori', 
        itemType: 'helmet', 
        plusDef: 14, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 3400,
        secondPrice: 3000,
        desc: "Even steel cannot penetrate the hardness of this steel",
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 9},
        cState: 4000,
        durability: 4000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Silver Shade",
        name: 'karpred', 
        itemType: 'helmet', 
        plusDef: 16, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 3400,
        secondPrice: 3000,
        desc: "A small shaded silver helmet, comfortable to wear and light but hard",
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 9},
        cState: 4000,
        durability: 4000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Silvered Nine",
        name: 'silverdnine', 
        itemType: 'gear', 
        plusDef: 10, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 100,
        secondPrice: 100,
        desc: "A well forged gear, useful for protection and light weight armor",
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 9},
        cState: 4000,
        durability: 4000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Copper Scale",
        name: 'copperScale', 
        itemType: 'gear', 
        plusDef: 10, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 100,
        secondPrice: 100,
        desc: "Gear that can blocked small attacks, can protect you from harm",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 9},
        cState: 4000,
        durability: 4000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Safe Shield",
        name: 'safeshield', 
        itemType: 'shield', 
        plusDef: 10, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 100,
        secondPrice: 100,
        desc: "A well forged gear, can break easily but can protect you",
        craftMaterial: { name: "gobcore", qnty: 3, forgeChance: 10},
        cState: 1500,
        durability: 1500,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Ancilian Shield",
        name: 'ancilia', 
        itemType: 'shield', 
        plusDef: 20, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 100,
        secondPrice: 100,
        desc: "A Heart Shaped Shield, Light and can block normal attacks",
        craftMaterial: { name: "mincore", qnty: 3, forgeChance: 9},
        cState: 2000,
        durability: 2000,
        rarity: 1,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Zviadi Iron",
        name: 'zviadi', 
        itemType: 'shield', 
        plusDef: 35, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 100,
        secondPrice: 100,
        desc: "A special shield, Can Block some magic and good in blocking normal attacks",
        craftMaterial: { name: "vipcore", qnty: 2, forgeChance: 9},
        cState: 3000,
        durability: 3000,
        rarity: 2,
        notLootIn: ["dungeon"]
    },
    {
        dn: "Goblin Core",
        name: 'gobcore', 
        for: "goblin",
        itemType: 'core', 
        plusDef: 0, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 100,
        secondPrice: 100,
        desc: "This core has a chaotic green color and can be good quality sometimes.",
        rarity: 0,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: "Golem Core",
        name: 'golemcore', 
        for: "golem",
        itemType: 'core', 
        plusDef: 0, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 100,
        secondPrice: 100,
        desc: "One of the robust core you can found, Some craftsmen enjoy using this tool. Steeming with light on its core this core is one of a kind",
        rarity: 0,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: "Minotaur Core",
        name: 'mincore', 
        for: "minotaur",
        itemType: 'core', 
        plusDef: 0, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 300,
        secondPrice: 200,
        desc: "This is one of the favorite core of craftsmen to make their weapons, quality is good",
        rarity: 1,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: "Viper Core",
        name: 'vipcore', 
        for: "viper",
        itemType: 'core', 
        plusDef: 0, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 1000,
        secondPrice: 500,
        desc: "The Viper's core can sometimes dangerous for its toxins lives inside its core. better be careful handling it",
        rarity: 2,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: "bluemin Core",
        name: 'bluemincore', 
        for: "bluedemon",
        itemType: 'core', 
        plusDef: 0, plusDmg: 0, 
        magRes: 0, plusMag: 0,
        origPrice: 3000,
        secondPrice: 1500,
        desc: "A core that can be found in demons, normally from blue horn demons",
        rarity: 3,
        notLootIn: ["dungeon", "heartland"]
    },
    {
        dn: "Flow Stamina",
        name: 'stam1',
        itemType: 'flower',
        origPrice: 30,
        secondPrice: 20,
        rarity: 0,
        notLootIn: ["dungeon"],
        desc: "Widely use for creating stamina potions to replenish stamina of the user"
    },
    {
        dn: "Lotus Herb",
        name: 'lotusHerb',
        itemType: 'herbs',
        origPrice: 30,
        secondPrice: 20,
        rarity: 0,
        notLootIn: ["dungeon"],
        desc: "Useful for creating potions, can also be used to make medicines"
    },
    {
        dn: 'Wood',
        name: "wood",
        itemType: "tool",
        desc: "used for making bon fire and can make stick out of it",
        origPrice: 2,
        secondPrice: 1,
        rarity: 0,
        notLootIn: ["dungeon"]
    },
    {
        dn: 'Iron',
        name: "iron",
        itemType: "tool",
        desc: "essential for making swords and hard tools",
        origPrice: 5,
        secondPrice: 2,
        rarity: 0,
        notLootIn: ["heartland"]
    },
]

export default records