const toSell = [
    { 
        name: 'bladefury',
        dn: 'Blade Fury',
        itemType: 'sword',
        desc: "a fury sword used by old heroes",
        price: 4900,
        plusDmg: 37,
        cState: 1400,
        durability:1400,
    },
    { 
        name: 'huntingsword',
        dn: 'Hunting Sword',
        itemType: 'sword',
        desc: "sword used for hunting boar and small monsters",
        price: 2600,
        plusDmg: 15,
        cState: 1000,
        durability:1000,
    },
    { 
        name: 'dragonSpear',
        dn: 'Dragon Spear',
        itemType: 'sword',
        desc: "holding this powerful spear can make you powerful against any foes",
        price: 6000,
        plusDmg: 40,
        cState: 3000,
        durability:3000,
    },
    { 
        name: 'villageSpear',
        dn: 'Village Spear',
        itemType: 'sword',
        desc: "A Pointed Spear useful for throwing, good for hunting",
        price: 800,
        plusDmg: 10,
        cState: 500,
        durability:500
    },
    { 
        name: 'dgerSpear',
        dn: 'Dger Spear',
        itemType: 'sword',
        desc: "Light and easy to throw spear, It camouflages in the dark",
        price: 3000,
        plusDmg: 30,
        cState: 4000,
        durability:4000,
    },
    { 
        name: 'drakfoid',
        dn: 'Drakfoid',
        itemType: 'sword',
        desc: "A sword that on par to it's kind the sword can slay hundreds of demons",
        price: 3800,
        plusDmg: 40,
        cState: 4000,
        durability:4000,
    },
    { 
        name: 'grimblue',
        dn: "Grim Blue",
        itemType: 'sword',
        desc: "one of its kind, crafted my the great maggos in its time",
        price: 5400,
        plusDmg: 45,
        cState: 4000,
        durability:4000,
    },
    { 
        name: 'ruztysword',
        dn: "Ruzty Sword",
        itemType: 'sword',
        desc: "it's rust can inflict your enemy with tetano",
        price: 4400,
        plusDmg: 35,
        cState: 4000,
        durability:4000,
    },
    { 
        name: 'stick',
        dn: "Stick",
        itemType: 'sword',
        desc: "useful weapon for self defense can still damage enemy",
        price: 1400,
        plusDmg: 8,
        cState: 500,
        durability:500,
    },
    { 
        name: 'sarpion',
        dn: "Sarpion Saver",
        itemType: 'sword',
        desc: "A heavy pointed sword, No mercy on your enemy",
        price: 5000,
        plusDmg: 40,
        cState: 4000,
        durability:4000,
    },
    { 
        name: 'rod',
        dn: "Iron rod",
        itemType: 'sword',
        desc: "A heavy swing from the user will create a large impact on the enemy",
        price: 2000,
        plusDmg: 12,
        cState: 2000,
        durability:2000,
    },
    { 
        name: 'pickaxe',
        dn: "Pickaxe",
        itemType: 'sword',
        desc: "Essential for minning and can also be used as a weapon",
        price: 2000,
        plusDmg: 10,
        cState: 10000,
        durability:10000,
    },
    {
        name: 'hydra',
        dn: "Hydra Armor",
        itemType: 'armor', 
        plusDef: 30, plusDmg: 0, 
        magRes: 10, plusMag: 0,
        price: 6000,
        cState: 6200,
        durability:6200,
        desc: "a noble's armor the armor is light but strong as destruction"
    },
    {
        name: 'chiefplate',
        dn: "Chief Plate",
        itemType: 'armor', 
        plusDef: 10, plusDmg: 0, 
        magRes: 10, plusMag: 0,
        price: 5000,
        cState: 5190,
        durability:5190,
        desc: "a replica of Chief Hanzon armor, the plate is made by bronze"
    },
    {
        name: 'karba',
        dn: "Karba Armor",
        itemType: 'armor', 
        plusDef: 39, plusDmg: 0, 
        magRes: 8, plusMag: 0,
        price: 7100,
        cState: 7000,
        durability:7000,
        desc: "As shining as heaven, this armor was made by a supreme deity to prevent fatal death"
    },
    {
        name: 'firstborn',
        dn: "FirstBorn Helmet",
        itemType: 'helmet', 
        plusDef: 10, plusDmg: 0, 
        magRes: 8, plusMag: 0,
        price: 2400,
        cState: 3900,
        durability:3900,
        desc: "You use this helmet if you're out for adventuring."
    },
    {
        name: 'karori',
        dn: "karori",
        itemType: 'helmet', 
        plusDef: 40, plusDmg: 0, 
        magRes: 8, plusMag: 0,
        price: 5600,
        cState: 4000,
        durability:4000,
        desc: ""
    },
    {
        name: 'silverdnine', 
        dn: 'Silvered Nine',
        itemType: 'gear', 
        plusDef: 20, plusDmg: 0, 
        magRes: 8, plusMag: 0,
        price: 3000,
        cState: 3500,
        durability:3500,
        desc: "A well forged gear, useful for protection and light weight armor"
    },
    {
        name: 'copperScale', 
        dn: 'Copper Scale',
        itemType: 'gear', 
        plusDef: 5,
        price: 900,
        cState: 2500,
        durability:2500,
        desc: "Gear that can blocked small attacks, can protect you from harm"
    },
    {
        name: 'safeshield', 
        dn: 'Safe Shield',
        itemType: 'shield', 
        plusDef: 20, plusDmg: 0, 
        magRes: 8, plusMag: 0,
        price: 3000,
        cState: 2000,
        durability:2000,
        desc: ""
    },
    {
        name: 'poisonAntidote', 
        dn: 'Atropine',
        itemType: 'food',
        price: 300,
        desc: "This antidote is best used for poisons, Only good herbal expert can craft such antidote"
    }  
]

export default toSell